name: Crear Nuevo Cliente

on:
  push:
    branches:
      - feature/cliente-nuevo

jobs:
  crear_cliente:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Crear cliente
      run: echo "Comando para crear nuevo cliente"

name: Modificar Cliente

on:
  push:
    branches:
      - feature/modificar-cliente

jobs:
  modificar_cliente:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Modificar cliente
      run: echo "Comando para modificar cliente"


name: Consultar Cliente

on: 
  workflow_dispatch:
    inputs:
      clienteId:
        description: 'ID del Cliente'
        required: true

jobs:
  consulta_cliente:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Consultar cliente
      run: echo "Consulta cliente con ID ${{ github.event.inputs.clienteId }}"

  name: Solicitud de Mejora

on: 
  workflow_dispatch:
    inputs:
      descripcion:
        description: 'Descripción de la Mejora'
        required: true

jobs:
  solicitud_mejora:
    runs-on: ubuntu-latest
    steps:
    - name: Registro de solicitud
      run: echo "Solicitud de mejora registrada: ${{ github.event.inputs.descripcion }}"
name: Modificación de Código

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: echo "Ejecutar pruebas y build"
name: Solicitud de Nueva Función

on: 
  workflow_dispatch:
    inputs:
      funcion:
        description: 'Descripción de la Nueva Función'
        required: true

jobs:
  solicitud_funcion:
    runs-on: ubuntu-latest
    steps:
    - name: Registro de nueva función
      run: echo "Nueva función solicitada: ${{ github.event.inputs.funcion }}"
c

